# Generated by Django 4.2.16 on 2024-10-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'ตั๋ว', 'verbose_name_plural': 'ตั๋ว'},
        ),
    ]
