# Generated by Django 4.2.16 on 2024-10-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketlog',
            options={'ordering': ['-created']},
        ),
    ]
