# Generated by Django 4.2.16 on 2024-11-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='start_date',
        ),
    ]
