# Generated by Django 4.2.16 on 2024-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
